HairColors: 
- Dashes: 0 
  Color: "ABCDEF"
- Dashes: 1 
  Color: "F501A1"
- Dashes: 2 
  Color: "6B1DC2"
- Dashes: 3 
  Color: "28EC37"
- Dashes: 4 
  Color: "FFFA45"
- Dashes: 5 
  Color: "FFFA45"
- Dashes: 6
  Color: "FFFA45"
- Dashes: 7
  Color: "FFFA45"